name: "ll_project"
type: "python:3.11"

relationships:
    database: "db:postgresql"

web:
    upstream:
        socket_family: unix
    commands:
        start: "gunicorn -w 4 -b unix:$SOCKET ll_project.wsgi:application"
    locations:
        "/":
            passthru: true
        "/static":
            root: "staticfiles"
            expires: 1h
            allow: true

disk: 512

mounts:
    "logs":
        source: local
        source_path: logs

hooks:
    build: |
        pip install --upgrade pip
        pip install -r requirements.txt
        # Remove this if you don't actually have requirements_remote.txt
        # pip install -r requirements_remote.txt

        mkdir -p logs
        python manage.py collectstatic --noinput
        rm -rf logs
    deploy: |
        python manage.py migrate

        